### ISSUE TITLE
Error when running app.js

### ISSUE THREAD

**Issue by nishanth6** [ranchor/socket-node-mysql-codeigniter-chat-1#6]
**node app.js**

```
C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-master>node app.js
C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-master\node_modules\socket.
io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-
master\node_modules\socket.io\lib\store.js:35:42)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-
master\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-master>npm install
npm WARN deprecated connect@2.9.0: connect 2.x series is deprecated

> ws@0.4.32 install C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-master\
node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-master\node_modules\ws>if n
ot defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\n
ode_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_module
s\node-gyp\bin\node-gyp.js" rebuild )
npm WARN saveError ENOENT: no such file or directory, open 'C:\xampp\htdocs\sock
et-node-mysql-codeigniter-chat-1-master\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\socket-
node-mysql-codeigniter-chat-1-master\package.json'
npm WARN socket-node-mysql-codeigniter-chat-1-master No description
npm WARN socket-node-mysql-codeigniter-chat-1-master No repository field.
npm WARN socket-node-mysql-codeigniter-chat-1-master No README data
npm WARN socket-node-mysql-codeigniter-chat-1-master No license field.

added 40 packages from 34 contributors, removed 35 packages, updated 5 packages
and audited 67 packages in 72.35s
found 21 vulnerabilities (7 low, 6 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-master>node app.js
C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-master\node_modules\socket.
io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-
master\node_modules\socket.io\lib\store.js:35:42)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\xampp\htdocs\socket-node-mysql-codeigniter-chat-1-
master\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

**Comment by Abdul916** [comment]
When i am Running App.js
$ node app
F:\xampp\htdocs\chatci1\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (F:\xampp\htdocs\chatci1\node_modules\←[4msocket.io←[24m\lib\store.js:35:42)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:77:18)←[39m
    at Object.<anonymous> (F:\xampp\htdocs\chatci1\node_modules\←[4msocket.io←[24m\lib\manager.js:16:13)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)←[39m

please guide me for resolving this issue

**Comment by pankujoshi** [comment]
please guide me for resolving same issue

**Comment by pankujoshi** [comment]
Hy i have found solution .   replace EventEmitter.prototype to  EventEmitter = require('events')  in every file
